// <auto-generated />
using CaddyShackMVC.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaddyShackMVC.Migrations
{
    [DbContext(typeof(CaddyShackContext))]
    partial class CaddyShackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaddyShackMVC.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GolfBagId")
                        .HasColumnType("integer")
                        .HasColumnName("golf_bag_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_clubs");

                    b.HasIndex("GolfBagId")
                        .HasDatabaseName("ix_clubs_golf_bag_id");

                    b.ToTable("clubs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GolfBagId = 1,
                            Name = "Driver"
                        },
                        new
                        {
                            Id = 2,
                            GolfBagId = 1,
                            Name = "Putter"
                        },
                        new
                        {
                            Id = 3,
                            GolfBagId = 1,
                            Name = "5 Iron"
                        },
                        new
                        {
                            Id = 4,
                            GolfBagId = 2,
                            Name = "Driver"
                        },
                        new
                        {
                            Id = 5,
                            GolfBagId = 2,
                            Name = "Putter"
                        },
                        new
                        {
                            Id = 6,
                            GolfBagId = 2,
                            Name = "9 Iron"
                        });
                });

            modelBuilder.Entity("CaddyShackMVC.Models.GolfBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player");

                    b.HasKey("Id")
                        .HasName("pk_golf_bags");

                    b.ToTable("golf_bags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 18,
                            Player = "Sung-jae Im"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 14,
                            Player = "Lydia Ko"
                        });
                });

            modelBuilder.Entity("CaddyShackMVC.Models.Club", b =>
                {
                    b.HasOne("CaddyShackMVC.Models.GolfBag", "GolfBag")
                        .WithMany("Clubs")
                        .HasForeignKey("GolfBagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clubs_golf_bags_golf_bag_id");

                    b.Navigation("GolfBag");
                });

            modelBuilder.Entity("CaddyShackMVC.Models.GolfBag", b =>
                {
                    b.Navigation("Clubs");
                });
#pragma warning restore 612, 618
        }
    }
}
